#task1


In [84]:
import numpy as np
matrix=np.array([[1,2,5],[5,6,3],[7,4,9]])
def get_inverse(matrix):
    try:
        inverse = np.linalg.inv(matrix)
        return inverse
    except np.linalg.linalgError:
        print("matrix is singular and does not have an inverse.")
        return none
inverse_matrix=get_inverse(matrix)
print("original matrix:")
print(matrix)
print("\nInverse matrix:")
print(inverse_matrix)
 #dominant value function   

original matrix:
[[1 2 5]
 [5 6 3]
 [7 4 9]]

Inverse matrix:
[[-0.36206897 -0.01724138  0.20689655]
 [ 0.20689655  0.22413793 -0.18965517]
 [ 0.18965517 -0.0862069   0.03448276]]


In [80]:
#identify matrix function

def identity_matrix(matrix):
    n= len(matrix)
    id_matrix=[[1 if i==j else 0 for j in range(n)]for i in range(n)]
    return id_matrix
matrix=[[1,2,3],[4,5,6],[7,8,9]]
id_matrix= identity_matrix(matrix)
print("Input matrix")
for row in matrix:
    print(row)
print("\nIdentity matrix:")
for row in id_matrix:
    print(row)


Input matrix
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]

Identity matrix:
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [ ]:
#